// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOzJz3QhUo5pFQM1e4jNKCvOQnJ8hRvE0',
    appId: '1:1080682481102:web:4770fbb77fc2759ebb579f',
    messagingSenderId: '1080682481102',
    projectId: 'fasum-4f39c',
    authDomain: 'fasum-4f39c.firebaseapp.com',
    databaseURL: 'https://fasum-4f39c-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-4f39c.firebasestorage.app',
    measurementId: 'G-CXVE0R71H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgxvMTLcgRghhGf1DBQXXpm50QiSaTges',
    appId: '1:1080682481102:android:1d6564b7df48566cbb579f',
    messagingSenderId: '1080682481102',
    projectId: 'fasum-4f39c',
    databaseURL: 'https://fasum-4f39c-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-4f39c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8QYWhsDEvFQaz4NCUIpaw4eZgJaY6-qU',
    appId: '1:1080682481102:ios:c575395d8427a81dbb579f',
    messagingSenderId: '1080682481102',
    projectId: 'fasum-4f39c',
    databaseURL: 'https://fasum-4f39c-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-4f39c.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8QYWhsDEvFQaz4NCUIpaw4eZgJaY6-qU',
    appId: '1:1080682481102:ios:c575395d8427a81dbb579f',
    messagingSenderId: '1080682481102',
    projectId: 'fasum-4f39c',
    databaseURL: 'https://fasum-4f39c-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-4f39c.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOzJz3QhUo5pFQM1e4jNKCvOQnJ8hRvE0',
    appId: '1:1080682481102:web:6e5f623f30d12b83bb579f',
    messagingSenderId: '1080682481102',
    projectId: 'fasum-4f39c',
    authDomain: 'fasum-4f39c.firebaseapp.com',
    databaseURL: 'https://fasum-4f39c-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-4f39c.firebasestorage.app',
    measurementId: 'G-4XXRMR6SGJ',
  );
}
